/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rabbitMQPipelineTesting.app;

/*
import rabbitMQPipelineTesting.list.LinkedList;

import static rabbitMQPipelineTesting.utilities.StringUtils.join;
import static rabbitMQPipelineTesting.utilities.StringUtils.split;
import static rabbitMQPipelineTesting.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;
 */
import org.json.JSONObject;

public class App {
    public static void main(String[] args) {

       JSONObject jo = new JSONObject("{ \"abc\" : \"def\" }");
       System.out.println(jo.toString());


    }
}
